// KNOWN-ANSWER TEST pinning the copied SigV4 presigner to the studio original (cf#85).
//
// tests/r2-presign-sigv4.ts is a deliberate copy of vivijure-cf src/r2-presign.ts, taken because the
// extraction contract forbids source-level imports across the repo seam. A copy with no pin is the
// drift risk this extraction is supposed to eliminate, so these vectors were GENERATED BY RUNNING THE
// ORIGINAL at vivijure-cf commit 59b3fb382521cab36cc0a746f77b174635133552 and are asserted here.
//
// If this test ever fails, the copy has diverged from the signing behaviour the studio shipped.
// Do NOT re-baseline the expected strings to make it pass: regenerate them from the studio source
// and confirm the change was intentional there first.
//
// The clock is pinned (nowMs) because SigV4 folds the timestamp into the signature.

import { describe, it, expect } from "vitest";
import { presignR2WithConfig, uriEncode, type R2PresignConfig } from "./r2-presign-sigv4";

const CFG: R2PresignConfig = {
  accessKeyId: "AKIAEXAMPLEKEYID0000",
  secretAccessKey: "wJalrXUtnFEMIexampleKEYexampleKEYexample",
  endpoint: "https://acct123.r2.cloudflarestorage.com",
  bucket: "vivijure-renders",
};
const NOW_MS = Date.parse("2026-01-02T03:04:05.000Z");

describe("R2 SigV4 presign, pinned to the studio original", () => {
  it("signs a GET byte-for-byte as vivijure-cf does", async () => {
    const url = await presignR2WithConfig(CFG, "GET", "tenant/abc/film 1.mp4", 300, NOW_MS);
    expect(url).toBe(
      "https://acct123.r2.cloudflarestorage.com/vivijure-renders/tenant/abc/film%201.mp4" +
        "?X-Amz-Algorithm=AWS4-HMAC-SHA256" +
        "&X-Amz-Credential=AKIAEXAMPLEKEYID0000%2F20260102%2Fauto%2Fs3%2Faws4_request" +
        "&X-Amz-Date=20260102T030405Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host" +
        "&X-Amz-Signature=c6cbbefb380462f4f0a8b6edddabbcd6ff59b7220b660251108258c18a9d2fca",
    );
  });

  it("signs a PUT byte-for-byte as vivijure-cf does", async () => {
    const url = await presignR2WithConfig(CFG, "PUT", "a/b/c.png", 300, NOW_MS);
    expect(url).toBe(
      "https://acct123.r2.cloudflarestorage.com/vivijure-renders/a/b/c.png" +
        "?X-Amz-Algorithm=AWS4-HMAC-SHA256" +
        "&X-Amz-Credential=AKIAEXAMPLEKEYID0000%2F20260102%2Fauto%2Fs3%2Faws4_request" +
        "&X-Amz-Date=20260102T030405Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host" +
        "&X-Amz-Signature=73ffc512309b90fe3f4e533ce78eb8aad7f2a6106558712265825ae67046ac60",
    );
  });

  // NEGATIVE CONTROL: the guard must actually refuse, and it must refuse the REAL unsafe shapes.
  // Watch it fail before trusting it (verification doctrine). Non-ASCII cases use \u escapes so the
  // file stays pure ASCII on disk.
  it.each([
    ["parent traversal", "a/../../etc/passwd"],
    ["absolute key", "/etc/passwd"],
    ["scheme injection", "https://evil.example/x"],
    ["control char", "a/\u0001b"],
    ["DEL", "a/\u007fb"],
    ["non-ascii", "a/\u00e9.png"],
    ["empty", ""],
  ])("refuses to sign an unsafe key (%s)", async (_label, key) => {
    await expect(presignR2WithConfig(CFG, "GET", key, 300, NOW_MS)).rejects.toThrow(/unsafe object key/);
  });

  // POSITIVE CONTROL for the guard: proves the refusals above are the guard working, not the
  // signer being incapable of succeeding at all (a negative suite over a dead capability all passes).
  it("still signs keys that are merely unusual but safe", async () => {
    await expect(presignR2WithConfig(CFG, "GET", "a b/c#d.png", 300, NOW_MS)).resolves.toContain(
      "X-Amz-Signature=",
    );
  });

  it("encodes slashes per S3 canonical rules", () => {
    expect(uriEncode("a/b", false)).toBe("a/b");
    expect(uriEncode("a/b", true)).toBe("a%2Fb");
  });
});
